config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#if_api_usage_limit'
  # get 'search_stock', to: 'stocks#search'

  resources :friendships, only: [:create, :destroy]
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search_user_friend'

  resources :users, only: [:show], :constraints => { :id => /[0-9|]+/ } #um estudante disse que se não fizer assim pode dar conflito com devise (edit creio)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
require 'httparty'

class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.company_lookup(ticker_symbol)
    response = HTTParty.get("https://www.alphavantage.co/query?function=OVERVIEW&symbol=#{ticker_symbol}&apikey=#{Rails.application.credentials.alphavantage_client[:alpha_api_key]}")
    if response.code == 200 && response.parsed_response['Name'].present?
      response.parsed_response['Name']
    else
      nil
    end
  end

  def self.new_lookup(ticker_symbol)
    response = HTTParty.get("https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=#{ticker_symbol}&apikey=#{Rails.application.credentials.alphavantage_client[:alpha_api_key]}")
    if response.code == 200 && response.parsed_response['Global Quote'] && response.parsed_response['Global Quote']['05. price'].present?
      last_price = response.parsed_response['Global Quote']['05. price']
      name = company_lookup(ticker_symbol)
      return nil if name.nil? || last_price.nil?
      new(ticker: ticker_symbol, name: name, last_price: last_price)
    else
      nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, length: {minimum:3, maximum: 20}       
  validates :last_name, length: {minimum:3, maximum: 20}       


  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end
  
  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end
  
  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Usuário"
  end

  def self.search(entry)
    entry.strip!
    return nil if entry.empty?
  
    where(
      "LOWER(first_name) LIKE :entry OR LOWER(last_name) LIKE :entry OR LOWER(email) LIKE :entry OR CONCAT(LOWER(first_name), ' ', LOWER(last_name)) LIKE :entry",
      entry: "%#{entry.downcase}%"
    ).distinct
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
  
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: params[:friend])
    if current_user.save
      flash[:notice] = "Você está seguindo #{friend.full_name}!"
    else
      flash[:alert] = "Algo de errado aconteceu..."
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Você parou de seguir #{friendship.friend.full_name}"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    @user = current_user
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        @tracked_stocks = current_user.stocks
        render 'users/my_portfolio'
      else
        flash[:alert] = 'Por favor insira uma sigla válida.'
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = 'Por favor insira uma sigla para pesquisar.'
      redirect_to my_portfolio_path
    end
  end

  def if_api_usage_limit
    @user = current_user
    if params[:stock].present?
      @stock = Stock.find_by(ticker: params[:stock])
      if @stock
        @tracked_stocks = current_user.stocks
        render 'users/my_portfolio'
      else
        flash[:alert] = 'Por favor insira uma sigla válida.'
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = 'Por favor insira uma sigla para pesquisar.'
      redirect_to my_portfolio_path
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    # if stock.blank?
    #   stock = Stock.new_lookup(params[:ticker])
    #   stock.save
    # end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Ação #{stock.name} foi adicionado ao seu portfólio com sucesso!"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} foi removido do portfólio com sucesso."
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @user_friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search_user_friend
    entry = params[:friend] 
   
    if entry.present?
      @friends = User.search(entry).to_a #teve que passar pra array pois dava conflito com o delete e distinct no model
      @friends.delete(current_user)
      if @friends && !@friends.empty?
        @user_friends = current_user.friends
        render 'users/my_friends'
      else
        flash[:alert] = 'Usuário não encontrado.'
        redirect_to my_friends_path
      end
    else
      flash[:alert] = 'Por favor insira um nome ou e-mail para pesquisar.'
      redirect_to my_friends_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Sobrenome</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @user_friends.each do |friend| %>
          <tr>
            <td>
              <% if !friend.first_name %>
                Usuário
              <% else %>
                <%= friend.first_name %>
              <% end %>
              </td>
            <td><%= friend.last_name %></td>
            <td>
              <%= link_to 'Ver Perfil', user_path(friend), class: "btn btn-sm btn-success" %>
              <button type="button" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#modal-<%= friend.id %>">
                Deixar de seguir
              </button>
            </td>
          </tr>

          <div class="modal fade" id="modal-<%= friend.id %>" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="modalLabel-<%= friend.id %>" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalLabel-<%= friend.id %>">Confirme exclusão</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Tem certeza que quer deixar de seguir <strong><%= friend.full_name %></strong>?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                  <%= button_to 'Deixar de seguir', friendship_path(friend), method: :delete, class: 'btn btn-danger' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class='alert alert-success'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class='alert alert-danger'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Finance Tracker", root_path, class: "navbar-brand" %>
    
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to "Meu Portfólio", my_portfolio_path, class: "nav-link" %>
          </li>

          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <%= link_to 'Seguindo', my_friends_path, class: 'nav-link' %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Perfil
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to user_path(current_user), class: "dropdown-item" do %>
                <%= fa_icon 'user' %> Meu Perfil
              <% end %>
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <%= fa_icon 'edit' %> Editar Perfil
              <% end %>
            </div>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto mr-2">
          <li class="nav-item user-name">
            <%= link_to user_path(current_user), class: "text-dark text-decoration-none" do %>
              <%= fa_icon 'user' %> <%= current_user.full_name.truncate(25) %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
          </li>
        </ul>
      <% end %>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar..." aria-label="Search">
        
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container mt-3">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Sigla</th>
          <th scope="col">Nome</th>
          <th scope="col">Preço</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>
              <% if current_user.can_track_stock?(stock.ticker)%>
                <div style="margin-top: 0px;">
                  <%= button_to 'Adicionar ao Portfólio', user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-success text-center" %>
                </div>
              <% elsif current_user != @user %>
                <div>
                  <span class="badge badge-secondary" style="margin-top: 7px;">
                    Você já está rastreando 
                    <% if !current_user.under_stock_limit? %>
                      10 ações!
                    <% end %>
                    <% if current_user.stock_already_tracked?(stock.ticker) %>
                      esta ação!
                    <% end %>
                  </span>
                </div>
              <% end %>
              <% if current_user == @user %>
                <button type="button" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#modal-<%= stock.ticker %>">
                  Remover
                </button>
              <% end %>
            </td>
          </tr>
          <div class="modal fade" id="modal-<%= stock.ticker %>" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="modalLabel-<%= stock.ticker %>" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalLabel-<%= stock.ticker %>">Confirme exclusão</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Tem certeza que quer deixar de rastrear <strong><%= stock.name %></strong> (<%= stock.ticker %>)?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                  <%= button_to 'Remover', user_stock_path(stock), method: :delete, class: 'btn btn-danger' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<% if @friends %>
  <div class="card card-header results-block mb-3">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Nome: </strong> <%= friend.full_name %></td>

            <td><strong class="ml-2">Ações: </strong> <%= link_to 'Ver Perfil', user_path(friend), class: "btn btn-sm btn-success" %></td>
            
            <% if current_user.not_friends_with?(friend.id) %>
              <td><%= button_to 'Seguir Usuário', friendships_path(friend: friend), class: "btn btn-sm btn-success" %></td>
            <% else %>
            <td>
              <span class="badge badge-secondary">
                Já está seguindo este usuário!
              </span>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="card card-header results-block mb-3">
    <div class="d-flex justify-content-between">
      <div style="margin-top: 5px">
        <strong>Sigla: </strong> <%= @stock.ticker %>
        <strong>Nome: </strong> <%= @stock.name %>
        <strong>Preço: </strong> <%= @stock.last_price %>
      </div>
      <% if current_user.can_track_stock?(@stock.ticker)%>
        <div style="margin-top: 0px; margin-left: 30px">
          <%= button_to 'Adicionar ao Portfólio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success text-center" %>
        </div>
      <% else %>  
      <div>
        <span class="badge badge-secondary" style="margin-top: 7px; margin-left: 10px">
          Você já está rastreando 
          <% if !current_user.under_stock_limit? %>
            10 ações!
          <% end %>
          <% if current_user.stock_already_tracked?(@stock.ticker) %>
            esta ação!
          <% end %>
        </span>
      </div>
      <% end %>  
    </div>
  </div>
<% end %>

app/views/users/my_friends.html.erb
<h1>Seguindo</h1>

<div class='search-area'>
  <h3>Procurar Usuário</h3>
  <%= form_tag search_friend_path, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Insira o nome ou e-mail do usuário", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'users/friend_result' %>

<% if !@user_friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>Meu Portfólio</h1>
<div class='search-area'>
  <h3>Procurar Ações</h3>
  <%= form_tag search_stock_path, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Insira a Sigla da ação que você deseja consultar", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'users/result' %>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2 class="mb-4">Detalhes do Usuário</h2>

<div class="card card-header results-block mb-5">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Nome: </strong> <%= @user.full_name %></td>
        <% if current_user.id == @user.id %>
            <td><strong>Email: </strong> <%= @user.email %></td>
        <% end %>    
        <td>
        <% if current_user.id != @user.id %>
            <td>
              <% if current_user.not_friends_with?(@user.id) %>
                <%= button_to 'Seguir Usuário', friendships_path(friend: @user), class: "btn btn-sm btn-success" %>
              <% else %>
                <span class="badge badge-secondary">
                  Já está seguindo este usuário!
                </span>
              <% end %>
            </td>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<h2>Atualmente rastreando:</h2>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% else %>
    <% if current_user.id == @user.id %>
        <p class='lead'>Você não está rastreando uma ação no momento.</p>
    <% else %>
        <p class='lead'>Este usuário não está rastreando uma ação no momento.</p>
    <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Bem-vindo(a) ao Finance Tracker!</h1>
<p>Um site onde você pode rastrear ações e acompanhá-las em tempo real.</p>